### ISSUE TITLE
Remove dangerous smoothing patch

### ISSUE THREAD

**Issue by Cirromulus** [pilsbot/pils_control#2]
The patch https://github.com/pilsbot/pils_control/commit/d64ea7c70966fa64bfaddc1b046c64407e93d8bd did solve our problem of intermittent message failures, but I consider this dangerous.
It should be removed as soon as https://github.com/pilsbot/teleop_acker_joy/issues/1 is solved.

**Comment by DarthBubi** [comment]
Since pilsbot/teleop_acker_joy#1 is resolved, we can close this one.
